add hw-3
alxmkh/hw-3 pull request #1
Opened 2022-08-27 11:17 UTC by alxmkh

2022-08-30 21:36 UTC, wayvy requested changes
Обрати внимание на то, что в зависимости не добавлен пакет 'classnames'.

Также у тебя дублируются запросы при загрузке страницы - смотри вкладку Network в devtools браузера. Постарайся это починить - скорее всего помогут useEffect или useCallback. Вероятно, какой-то компонент перерендеривается два раза - тут поможет console.log('render componentName') в компонентах перед return.

И еще, если будет время поправить - в момент скролла появляется лишний ползунок из-за отрисовки loader. Тут скорее всего поможет фиксированная высота контейнера.

2022-08-30 21:36 UTC, wayvy commented on src/config/constants.ts
> +  headerApiKey = {
Кажется, для github не требуется apiKey, соотвестенно можно удалить все, оставить только
`export const BASE_URL = "https://api.github.com";`
Константы лучше объявлять капсом.

Возможно, оно нужно для лимитов. Тогда все-равно стоит объявить две константы `BASE_URL` и `HEADER_API_KEY` и уже в компоненте проверять на `undefined` и выводить какое-то сообщение об ошибке для пользователя.

2022-08-30 21:36 UTC, wayvy commented on src/reportWebVitals.ts
> +const reportWebVitals = (onPerfEntry?: ReportHandler) => {
Это нужно? Может удалить?

2022-08-30 21:36 UTC, wayvy commented on src/store/GitHubStore/GitHubStore.ts
> +export default class GitHubStore {}
Кажется, это нигде не используется

2022-08-30 21:36 UTC, wayvy commented on src/utils/api.ts
> +    // }));
Такие комменты лучше удалять перед pull request

2022-08-30 21:36 UTC, wayvy commented on src/utils/types.ts
> +};
Для данных, полученных из апишки, можно типизировать только те поля, которые будут использованы дальше в коде.

2022-08-31 11:50 UTC, alxmkh reviewed
+

2022-08-31 11:57 UTC, alxmkhl approved these changes

2022-08-31 12:00 UTC, alxmkhl requested changes
+

2022-08-31 12:00 UTC, merged